config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :good_evaluations, only: [:create, :destroy]
    resources :bad_evaluations, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get 'category'
    end
    collection do
      post 'attach'
    end
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index

end

app/models/article.rb
class Article < ApplicationRecord
  with_options presence: true do
    validates :title, length: { maximum: 40 }
    validates :text, length: { maximum: 15000 }
  end

  # has_rich_text :text
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :good_evaluations, dependent: :destroy
  has_many :bad_evaluations, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def self.search(search)
    if search != ""
      Article.where('text LIKE(?) OR title LIKE(?) OR category_id LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Article.includes(:user).order("created_at DESC")
    end
  end

  def self.evaluation(articles_evaluation, articles)
    articles.each do |article|
      if article.good_evaluations.length + article.bad_evaluations.length != 0
        article_evaluation = 100 * article.good_evaluations.length / (article.good_evaluations.length + article.bad_evaluations.length)
        articles_evaluation << {score: article_evaluation, count: article.good_evaluations.length, name: article}
      else
        article_evaluation = 0
        articles_evaluation << {score: article_evaluation, count: article.good_evaluations.length, name: article}
      end
    end
  end

  def create_notification_like!(current_user)
    # すでに「お気に入り登録」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and article_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # お気に入り登録されていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        article_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するお気に入り登録の場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      article_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy] 
  before_action :move_to_index, only: [:edit, :update, :destroy] 

  def index
    @articles = Article.includes(:user).order("created_at DESC")
    @new_articles = Kaminari.paginate_array(@articles).page(params[:new_articles_page]).per(3)
    @favorites = Article.find(Favorite.group(:article_id).order('count(article_id) DESC').pluck(:article_id))
    @favorite_articles = Kaminari.paginate_array(@favorites).page(params[:favorite_articles_page]).per(3)
    articles_evaluation = []
    Article.evaluation(articles_evaluation, @articles)
    @goods = articles_evaluation.sort_by{ |a| -a[:score] }.sort_by{ |a| -a[:count] }.pluck(:name)
    @good_articles = Kaminari.paginate_array(@goods).page(params[:good_articles_page]).per(3)
    if user_signed_in?
      follow_users = current_user.followings
      follow_users_articles = []
      follow_users.each do |follow_user|
        follow_user.articles.each do |follow_user_article|
          follow_users_articles << follow_user_article
        end
      end
      @follow_users_articles = Kaminari.paginate_array(follow_users_articles.sort_by{ |a| -a[:id] }).page(params[:follow_users_articles_page]).per(3)
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = '記事を投稿しました'
      redirect_to root_path
    else
      flash.now[:alert] = '記事の投稿に失敗しました'
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
    if user_signed_in?
      @favorite = Favorite.find_by(user_id: current_user.id, article_id: params[:id])
      @good_evaluation = GoodEvaluation.find_by(user_id: current_user.id, article_id: params[:id])
      @bad_evaluation = BadEvaluation.find_by(user_id: current_user.id, article_id: params[:id])  
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = '記事を更新しました'
      redirect_to article_path(@article) 
    else
      flash.now[:alert] = '記事の更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:success] = '記事を削除しました'
    redirect_to root_path
  end

  def search
    @articles = Article.search(params[:keyword])
  end

  def category
    @num = params[:id].to_i
    @article = Article.find_by(category_id: params[:id])
    @articles = Article.where(category_id: params[:id]).order("created_at DESC")
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :image, :category_id).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def move_to_index
    if user_signed_in? && current_user.id != @article.user_id 
      redirect_to root_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/category.html.erb
<div class="page-title">
  <h1>カテゴリ：<%= Category.data[@num][:name] %></h1>
</div>

<div class="search-result-index">
  <% if @articles.length != 0 %>
    <%= render partial: 'shared/article_contents', locals: {articles: @articles} %>
  <% else %>
    <h1 class="search-result"><%= Category.data[@num][:name] %>に該当する記事は見つかりませんでした。</h1>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="page-title">
  <h1>記事を編集</h1>
</div>

<div class="article-input-form">
  <%= form_with model: @article, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="input-articles">
      <div class="article-form">
        <h3>タイトル</h3>
        <%= f.text_field :title, class:"input-article-title", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      </div>

      <div class="article-form">
        <h3>カバー画像(任意)</h3>
        <%= f.file_field :image %>
        <div id="cover-img-preview"></div>        
      </div>

      <div class="article-form">
        <h3>カテゴリ(任意)</h3>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
      </div>

      <div class="article-form">
        <h3>本文</h3>
        <%= f.text_area :text, class:"input-article-text", placeholder:"本文", rows:"20", maxlength:"15000", wrap:"soft" %>
      </div>

      <%= f.submit "記事を更新する", class:"submit-article-btn" %>
    </div>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="page-title">
  <h1>新規投稿記事</h1>
</div>
<div class="top-page-index" id="new_articles_page">
  <%= render partial: 'shared/article_contents', locals: {articles: @new_articles} %>
</div>
<div id="new_articles_page_btn">
  <%= paginate @new_articles, param_name: "new_articles_page", remote: true %>
</div>

<div class="page-title">
  <h1>人気記事</h1>
</div>
<div class="top-page-index" id="favorite_articles_page">
  <%= render partial: 'shared/article_contents', locals: {articles: @favorite_articles} %>
</div>
<div id="favorite_articles_page_btn">
  <%= paginate @favorite_articles, param_name: "favorite_articles_page", remote: true %>
</div>

<div class="page-title">
  <h1>評価の高い記事</h1>
</div>
<div class="top-page-index" id="good_articles_page">
  <%= render partial: 'shared/article_contents', locals: {articles: @good_articles} %>
</div>
<div id="good_articles_page_btn">
  <%= paginate @good_articles, param_name: "good_articles_page", remote: true %>
</div>

<% if user_signed_in? %>
  <div class="page-title">
    <h1>フォローしているユーザーの記事</h1>
  </div>
  <% if @follow_users_articles.length != 0 %>
    <div class="top-page-index" id="follow_users_articles_page">
      <%= render partial: 'shared/article_contents', locals: {articles: @follow_users_articles} %>
    </div>
    <div id="follow_users_articles_page_btn">
      <%= paginate @follow_users_articles, param_name: "follow_users_articles_page", remote: true %>
    </div>
  <% else %>
    <p class="non-message">現在フォローしているユーザーはいません</p>
  <% end %>
<% end %>

<%= link_to new_article_path do %>
  <div class="article-new-btn">
    <%= image_tag "article_new.png", class: "article-new-img", alt: "article-new-image" %>
    <p class="article-new-text">New Article</p>
  </div>
<% end %>

app/views/articles/index.js.erb
$('#new_articles_page').html("<%= escape_javascript(render partial: 'shared/article_contents', locals: {articles: @new_articles}) %>");
$('#new_articles_page_btn').html("<%= escape_javascript(paginate @new_articles, param_name: "new_articles_page", remote: true) %>");

$('#favorite_articles_page').html("<%= escape_javascript(render partial: 'shared/article_contents', locals: {articles: @favorite_articles}) %>");
$('#favorite_articles_page_btn').html("<%= escape_javascript(paginate @favorite_articles, param_name: "favorite_articles_page", remote: true) %>");

$('#good_articles_page').html("<%= escape_javascript(render partial: 'shared/article_contents', locals: {articles: @good_articles}) %>");
$('#good_articles_page_btn').html("<%= escape_javascript(paginate @good_articles, param_name: "good_articles_page", remote: true) %>");

<% if user_signed_in? %>
$('#follow_users_articles_page').html("<%= escape_javascript(render partial: 'shared/article_contents', locals: {articles: @follow_users_articles}) %>");
$('#follow_users_articles_page_btn').html("<%= escape_javascript(paginate @follow_users_articles, param_name: "follow_users_articles_page", remote: true) %>");
<% end %>

app/views/articles/new.html.erb
<div class="page-title">
  <h1>新規記事投稿</h1>
</div>

<div class="article-input-form">
  <%= form_with model: @article, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="input-articles">
      <div class="article-form">
        <h3>タイトル</h3>
        <%= f.text_field :title, class:"input-article-title", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      </div>

      <div class="article-form">
        <h3>カバー画像(任意)</h3>
        <%= f.file_field :image %>
        <div id="cover-img-preview"></div>
      </div>

      <div class="article-form">
        <h3>カテゴリ(任意)</h3>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
      </div>

      <div class="article-form">
        <h3>本文</h3>
        <%= f.text_area :text, class:"input-article-text", placeholder:"本文", rows:"20", maxlength:"15000", wrap:"soft" %>
      </div>

      <%= f.submit "記事を投稿する", class:"submit-article-btn" %>
    </div>
  <% end %>
</div>

app/views/articles/search.html.erb
<div class="page-title">
  <h1>検索結果</h1>
</div>

<div class="search-result-index">
  <% if @articles.length != 0 %>
    <h2 class="search-result"><%= @articles.length %>件ヒットしました。</h2>
    <%= render partial: 'shared/article_contents', locals: {articles: @articles} %>
  <% else %>
    <h1 class="search-result">検索結果が見つかりませんでした</h1>
  <% end %>
</div>

app/views/articles/show.html.erb
<% if user_signed_in? && current_user.id == @article.user_id %>
  <%= link_to edit_article_path(@article) do %>
    <%= image_tag "edit_img.png", class: "user-edit-img" %>
  <% end %>
    <%= image_tag "delete_img.png", class: "user-delete-img" %>
    <div class="delete-modal">
      <div class="modal-bg delete-modal-close"></div>
      <div class="delete-modal-content">
        <h2>記事を削除しますか？</h2>
        <div class="delete-content-btn">
          <%= link_to "はい", article_path(@article), method: :delete %>
          <a class="delete-modal-close">戻る</a>
        </div>
      </div>
    </div>
<% end %>

<div class="user-access">
  <%= link_to "#{@article.user.nickname}さんの記事をもっと見る", user_path(@article.user) %>
</div>

<%= render partial: "favorites/favorite_btn", locals: { article: @article, favorite: @favorite} %>

<%= render partial: "good_evaluations/good_btn", locals: { article: @article, good_evaluation: @good_evaluation} %>

<%= render partial: "bad_evaluations/bad_btn", locals: { article: @article, bad_evaluation: @bad_evaluation} %>

<div class="article-show-content">
  <div class="article-cover-img">
  <% if @article.image.attached? %>
    <%= image_tag @article.image, class: "header-img" %>
  <% else %>
    <%= image_tag "sample_img.jpg", class: "header-img" %>
  <% end %>
  </div>

  <div class="article-main">
    <div class="show-article-date">
      <p>投稿日 <%= l @article.created_at %></p>
      <% if @article.created_at != @article.updated_at %>
        <p>最終更新日 <%= l @article.updated_at %></p>
      <% end %>
    </div>

    <div class="show-article-title">
      <h1><%= @article.title %></h1>
    </div>

    <div class="article-text">
      <p><%= @article.text %></p>
    </div>

    <div class="article-comments-content">
    
      <% if user_signed_in? %>
        <div class="comment-content-form">
          <%= form_with model: @comment, url: article_comments_path(@article), local: true do |f| %>
            <%= render 'shared/error_messages', model: f.object %>
            <p>この記事に対するコメントを書く</p>
            <%= f.text_area :text, class:"input-article-comment", placeholder:"コメントを入力", rows:"5", maxlength:"250", wrap:"soft"%>
            <%= f.submit "コメントを送信", class:"comment-submit-btn" %>
          <% end %>
        </div>
      <% end %>

      <% if @comments.length != 0 %>
        <h2 class="comment-title">コメント</h2>
        <ul class=comment-lists>
          <% @comments.each do |comment| %>
            <li class=comment-list>
            <p><%= comment.text %></p>
            <p class="comment-user-name"><%= comment.user.nickname %>さん</p>
              <% if user_signed_in? && comment.user_id == current_user.id %>
              <%= link_to "コメントを削除", "/articles/#{@article.id}/comments/#{comment.id}", method: :delete, class: "comment-delete" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>この記事に対するコメントはまだありません</p>
      <% end %>
    </div>
  </div>
</div>