config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :good_evaluations, only: [:create, :destroy]
    resources :bad_evaluations, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get 'category'
    end
    collection do
      post 'attach'
    end
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  validates :user_id, presence: true
  validates :follow_id, presence: true
  
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def create
    following = current_user.follow(@user)
    following.save
    @user.create_notification_follow!(current_user)
  end

  def destroy
    following = current_user.unfollow(@user)
    following.destroy
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_btn.html.erb
<div class="follows">
  <% if user_signed_in? && current_user.following?(user) %>
    <%= form_with url: relationship_path(user), method: :delete, remote: true do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー中', class: 'follow-btn follow' %>
    <% end %>
  <% else %>
    <%= form_with url: relationships_path, remote: true do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローする', class: 'follow-btn unfollow' %>
    <% end %>
  <% end %>
</div>

app/views/relationships/_follow_btn_small.html.erb
<div class="follows-small" id="follows-small-<%=user.id%>">
  <% if current_user.following?(user) %>
    <%= form_with url: relationship_path(user), method: :delete, remote: true do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー中', class: 'follow-btn-small follow' %>
    <% end %>
  <% else %>
    <%= form_with url: relationships_path, remote: true do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローする', class: 'follow-btn-small  unfollow' %>
    <% end %>
  <% end %>
</div>

app/views/relationships/create.js.erb
$('.follows').html("<%= escape_javascript(render partial: "relationships/follow_btn", locals: {user: @user}) %>");
$('#follows-small-<%=@user.id%>').html("<%= escape_javascript(render partial: "relationships/follow_btn_small", locals: {user: @user}) %>");

app/views/relationships/destroy.js.erb
$('.follows').html("<%= escape_javascript(render partial: "relationships/follow_btn", locals: {user: @user}) %>");
$('#follows-small-<%=@user.id%>').html("<%= escape_javascript(render partial: "relationships/follow_btn_small", locals: {user: @user}) %>");