config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :good_evaluations, only: [:create, :destroy]
    resources :bad_evaluations, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get 'category'
    end
    collection do
      post 'attach'
    end
  end

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index

end

app/views/shared/_article_contents.html.erb
<ul class="articles-lists">
  <% articles.each do |article| %>
    <li class="article-list">
      <%= link_to article_path(article) do %>
        <div class="article-image-content">
          <% if article.image.attached? %>
            <%= image_tag article.image, class: "article-image", alt: "article-image" %>
          <% else %>
            <%= image_tag "sample_img.jpg", class: "article-image", alt: "article-image" %>
          <% end %>
        </div>
        <p class="article-title"><%= article.title.truncate(27) %></p>
      <% end %>

      <div class="article-middle">
        <p class="article-user"><%= link_to "by #{article.user.nickname}", user_path(article.user) %></p>
        <div class="article-icon">
          <% if user_signed_in? && Favorite.find_by(user_id: current_user.id, article_id: article.id) %> 
            <i class="fas fa-star favorite"></i>
          <% else %>
            <i class="fas fa-star unfavorite"></i>
          <% end %>
          <span class='count-num'><%= article.favorites.length %></span>

          <% if user_signed_in? && GoodEvaluation.find_by(user_id: current_user.id, article_id: article.id) %> 
            <i class="fas fa-thumbs-up"></i>
          <% else %>
            <i class="far fa-thumbs-up"></i>
          <% end %>
          <span class='count-num'><%= article.good_evaluations.length %></span>

          <% if user_signed_in? && BadEvaluation.find_by(user_id: current_user.id, article_id: article.id) %> 
            <i class="fas fa-thumbs-down"></i>
          <% else %>
            <i class="far fa-thumbs-down"></i>
          <% end %>
          <span class='count-num'><%= article.bad_evaluations.length %></span>
        </div>
      </div>
      <p class=article-category>カテゴリー：<%= article.category[:name]%></p>
    </li>
  <% end %>      
</ul>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class='footer-left'>
    <ul class="footer-list">
      <li class="footer-title">PosticleAppについて</li>
      <li>会社概要（運営会社）</li>
      <li>採用情報</li>
      <li>公式ブログ</li>
    </ul>
  </div>

  <div class='footer-center'>
    <ul class="footer-list">
      <li class="footer-title">プライバシーと利用規約</li>
      <li>プライバシーポリシー</li>
      <li>利用規約</li>
      <li>コンプライアンスポリシー</li>
    </ul>
  </div>

  <div class='footer-right'>
    <ul class="footer-list">
      <li><%= image_tag "https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class: "app-link" %></li>
      <li><%= image_tag "dl-android.png", class: "app-link" %></li>
      <i class="fab fa-twitter-square footer-icon"></i>
      <i class="fab fa-facebook-square footer-icon"></i>
      <i class="fab fa-line footer-icon"></i>
    </ul>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='header-left'>
  <%= image_tag "menu.png", id: "img-menu-icon" %>
    <%= link_to "PosticleApp", root_path, class: "header-logo" %>
  </div>

  <div id="modal-menu">
    <h3>カテゴリーから探す</h3>
    <ul class="category-list">
      <% Category.all.drop(1).each do |category| %>
        <li><%= link_to "#{category[:name]}", "/articles/#{category[:id]}/category", class: "category-link" %></li>
      <% end %>
    </ul>
  </div>

  <div class='header-center'>
    <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "記事を検索する", class: "search-input" %>
      <%= f.submit "検索", class: "search-btn" %>  
    <% end %>
  </div>

  <div class='header-right'>
    <%= image_tag "search.png", id: "search-image" %>
    <div class="search-modal">
      <div class="modal-bg search-modal-close"></div>
      <div class="search-modal-content">
        <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
          <%= f.text_field :keyword, placeholder: "記事を検索する", class: "search-input" %>
          <%= f.submit "検索", class: "search-btn" %>  
        <% end %>
      </div>
    </div>
    <% if user_signed_in? %>
      <%= link_to notifications_path do %>
        <div class="notifications-link header-right-list">
          <i class="fas fa-bell"></i>
          <% if current_user.passive_notifications.where(checked: false).count != 0 %>
          <div class='notifications-count'><%= current_user.passive_notifications.where(checked: false).count %></div>
          <% end %>
        </div>
      <% end %>
      <%= link_to current_user.nickname, user_path(current_user), class: 'header-right-list' %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'header-right-list' %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class: 'header-right-list' %>
      <%= link_to "新規登録", new_user_registration_path, class: 'header-right-list' %>
    <% end %>
  </div>
</header>